graphite:
    build: ./config
    
    stdin_open: true # docker run -i
    tty: true        # docker run -t

    restart: always
    ports:
        - "8080:80"
        - "8125:8125/udp"
        - "8126:8126"
        - "2003:2003"
        - "2004:2004"
    volumes:
        - "./data/graphite:/opt/graphite/storage"

grafana:
    image: grafana/grafana:latest-ubuntu
    restart: always
    ports:
        - "3000:3000"
    volumes:
        - "./data/grafana:/var/lib/grafana"
    links:
        - graphite
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=password
